package mobilityfeeds.gtfs

// Extended route types (Google / TPEG), used for trip_route_type
enum class GtfsExtendedRouteType(val value: Int) {
    RAILWAY_SERVICE(100),
    HIGH_SPEED_RAIL_SERVICE(101),
    LONG_DISTANCE_TRAINS(102),
    INTER_REGIONAL_RAIL_SERVICE(103),
    CAR_TRANSPORT_RAIL_SERVICE(104),
    SLEEPER_RAIL_SERVICE(105),
    REGIONAL_RAIL_SERVICE(106),
    TOURIST_RAILWAY_SERVICE(107),
    RAIL_SHUTTLE(108),
    SUBURBAN_RAILWAY(109),
    REPLACEMENT_RAIL_SERVICE(110),
    SPECIAL_RAIL_SERVICE(111),
    LORRY_TRANSPORT_RAIL_SERVICE(112),
    ALL_RAIL_SERVICES(113),
    CROSS_COUNTRY_RAIL_SERVICE(114),
    VEHICLE_TRANSPORT_RAIL_SERVICE(115),
    RACK_AND_PINION_RAILWAY(116),
    ADDITIONAL_RAIL_SERVICE(117),

    COACH_SERVICE(200),
    INTERNATIONAL_COACH_SERVICE(201),
    NATIONAL_COACH_SERVICE(202),
    SHUTTLE_COACH_SERVICE(203),
    REGIONAL_COACH_SERVICE(204),
    SPECIAL_COACH_SERVICE(205),
    SIGHTSEEING_COACH_SERVICE(206),
    TOURIST_COACH_SERVICE(207),
    COMMUTER_COACH_SERVICE(208),
    ALL_COACH_SERVICES(209),

    SUBURBAN_RAILWAY_SERVICE(300),

    URBAN_RAILWAY_SERVICE_400(400),
    METRO_SERVICE_401(401),
    UNDERGROUND_SERVICE_402(402),
    URBAN_RAILWAY_SERVICE_403(403),
    ALL_URBAN_RAILWAY_SERVICES(404),

    METRO_SERVICE(500),

    UNDERGROUND_SERVICE(600),

    BUS_SERVICE(700),
    REGIONAL_BUS_SERVICE(701),
    EXPRESS_BUS_SERVICE(702),
    STOPPING_BUS_SERVICE(703),
    LOCAL_BUS_SERVICE(704),
    NIGHT_BUS_SERVICE(705),
    POST_BUS_SERVICE(706),
    SPECIAL_NEEDS_BUS(707),
    MOBILITY_BUS_SERVICE(708),
    MOBILITY_BUS_FOR_REGISTERED_DISABLED(709),
    SIGHTSEEING_BUS(710),
    SHUTTLE_BUS(711),
    SCHOOL_BUS(712),
    SCHOOL_AND_PUBLIC_SERVICE_BUS(713),
    RAIL_REPLACEMENT_BUS_SERVICE(714),
    DEMAND_AND_RESPONSE_BUS_SERVICE(715),
    ALL_BUS_SERVICES(716),

    TROLLEYBUS_SERVICE(800),

    TRAM_SERVICE(900),
    CITY_TRAM_SERVICE(901),
    LOCAL_TRAM_SERVICE(902),
    REGIONAL_TRAM_SERVICE(903),
    SIGHTSEEING_TRAM_SERVICE(904),
    SHUTTLE_TRAM_SERVICE(905),
    ALL_TRAM_SERVICES(906),

    OTHER_SERVICES(1700);

    // Basic GTFS route_type this extended type refines: 0 tram, 1 subway, 2 rail, 3 bus, 11 trolleybus
    val basicRouteType: Int
        get() = when (value / 100) {
            1, 3 -> 2
            4, 5, 6 -> 1
            2, 7 -> 3
            8 -> 11
            9 -> 0
            else -> -1
        }
}
